[[bin]]
name = "c8rs"
path = "src/main.rs"

[package]
name = "c8rs"
version = "0.1.0"
edition = "2024"

[dependencies]
c8util = { workspace = true }
device_query = { workspace = true }

[lints]
workspace = true

