[package]
name = "c8rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
c8util = { workspace = true }
device_query = { workspace = true }

[lints]
workspace = true

